### ISSUE TITLE
panic: runtime error: cgo argument has Go pointer to Go pointer

### ISSUE THREAD

**Issue by phuongdo** [ma3axaka/catboost-go#2]
My code

```
  1 package main
  2
  3 import "fmt"
  4 import "github.com/ma3axaka/catboost-go"
  5 func main() {
  6     model, _:= catboost.LoadBinaryClassifierFromFile("catboost_demo.cbm")
  7      fmt.Println(err)
  8     numbers := [][]float32{{2.0, 3.0, 5.0, 7.0}}
  9     categories := [][]string{{"a", "b"}}
 10    prob, _ := model.PredictProba(numbers,4, categories,2)
 11    fmt.Println(prob)
 12 }
```

Here is the exception:
```
panic: runtime error: cgo argument has Go pointer to Go pointer

goroutine 1 [running]:
github.com/ma3axaka/catboost-go.(*Model).CalcModelPrediction.func2(0xc000010028, 0x1, 0xc000010038, 0x1, 0x1, 0x4, 0xc000010040, 0x1, 0x1, 0x2, ...)
	/home/phuongdv/gows/src/github.com/ma3axaka/catboost-go/model.go:99 +0xaf
github.com/ma3axaka/catboost-go.(*Model).CalcModelPrediction(0xc000010028, 0xc00009ff70, 0x1, 0x1, 0x4, 0xc00009ff58, 0x1, 0x1, 0x2, 0x0, ...)
	/home/phuongdv/gows/src/github.com/ma3axaka/catboost-go/model.go:99 +0x285
github.com/ma3axaka/catboost-go.(*BinaryClassifer).PredictProba(0xc00009ff30, 0xc00009ff70, 0x1, 0x1, 0x4, 0xc00009ff58, 0x1, 0x1, 0x2, 0x4a78c0, ...)
	/home/phuongdv/gows/src/github.com/ma3axaka/catboost-go/classifier.go:25 +0xab
main.main()

```

**Comment by lukangping** [comment]
I fix it in lukangping/catboost-go .
